# Instalación de paquetes para la práctica
install.packages(c("dplyr","kableExtra", "jsonlite"))
install.packages(c("systemfonts", "textshaping", "svglite"))
install.packages("kableExtra")

library(dplyr)
library(kableExtra)
library(jsonlite)

# Comienzo de la práctica
# Presentamos la tabla en HTML con las opciones de genoma de especies de Trypanosoma
library('kableExtra')
genomas <- read.table('trypanosoma_annotated.txt',
                      header = TRUE, sep = '\t')
kable(genomas) %>% kable_styling()

# Para ver los duplicados
duplicados <- duplicated(genomas)
print(duplicados)
table(duplicados)
  # Nos dice que hay 35 filas que dan FALSE en duplicado, osea que son únicas, 
  # y 0 filas duplicadas

# Ordenar listas, el codigo usado ordena el objeto que ya existe, no crea otro
order(help)
genomas <- genomas[order(genomas$Assembly.Release.Date), ]
kable(genomas) %>% kable_styling()
  # Ordenado por el año de lanzamiento del ensamblamiento, en ascendente

genomas$Assembly.Release.Date <- as.Date(genomas$Assembly.Release.Date,
                                         '%Y-%m-%d')
  # Esto permite atribuir a la columna de fecha de lanzamiento un valor de 
  # fecha, que no se lea como texto, sino como numero

# Aquí usamos "cumsum()" para obtener la suma acumulada del número de bases
# secuenciadas.
plot(x = genomas$Assembly.Release.Date,
     y = cumsum(genomas$Assembly.Stats.ATGC.Count),
     type = 'b',
     xlab = 'Fecha de publicación',
     ylab = 'Longitud total secuenciada (bp)',
     main = 'Genomas anotados de Trypanosoma')
  # Ahora que la columna de la que hablabamos se toma como una fecha podemos 
  # crear una tabla que saque por pantalla el numero de secuencias lanzadas
  # en cada año

# Ver los archivos jsnolines
library('jsonlite')
prettify(readLines('ncbi_dataset/data/assembly_data_report.jsonl'))

# Vamos a cargar en un dataframe la anotación del genoma que hemos escogido.
# Como no tiene cabecera, le damos los nombres de las columnas:
gff <- read.table('ncbi_dataset/data/GCA_022059095.1/genomic.gff', sep = '\t',
                  col.names = c('seqid', 'source', 'type', 'start', 'end',
                                'score', 'strand', 'phase', 'attributes'),
                  quote = '')
tail(gff)

unique(gff$type)

table(gff$type)

# Usamos un vector booleano como índice de las filas.
# En las tablas nuevas, no necesitamos la tercera columna y la eliminamos 
# con el "-3".

gene   <- gff[gff$type == 'gene',   -3]
mrna   <- gff[gff$type == 'mRNA',   -3]
exon   <- gff[gff$type == 'exon',   -3]
cds    <- gff[gff$type == 'CDS',    -3]
region <- gff[gff$type == 'region', -3]
  # Hemos creado 5 nuevos objetos correspondientes a cada valor de la variable
  # type en la tabla anterior.

# Alinear las órdenes nos ayuda a detectar posibles errores

# Para identificar en los marcos anteriores (objetos) que columnas tienen el
# mismo valor en todas las líneas y eliminarlas utilizaremos funciones del 
# paquete dplyr
gene   <- gene   %>% select(where(~ n_distinct(., na.rm = TRUE) > 1))
mrna   <- mrna   %>% select(where(~ n_distinct(., na.rm = TRUE) > 1))
exon   <- exon   %>% select(where(~ n_distinct(., na.rm = TRUE) > 1))
cds    <- cds    %>% select(where(~ n_distinct(., na.rm = TRUE) > 1))
region <- region %>% select(where(~ n_distinct(., na.rm = TRUE) > 1))
  # Modificamos cada objeto, no creamos nuevos, el codigo selecciona las
  # columnas de cada objeto y confirma si hay alguna fila que tenga valores 
  # diferentes, sino, son todos iguales, asi que lo elimina.
