---
title: "P10_ensamblaje"
lang: es
date: today
execute: 
  eval: true
  error: true
engine: knitr
bibliography: ../../doc/references.bib
language:
   title-block-published: "Última actualización:"
   section-title-references: "Bibliografía"
format:
   html:
      embed-resources: true
editor: 
  markdown: 
    wrap: 72
---

# Descarga de Hifiasm y datos

```{bash}
if [ ! -d ~/bin ]; then mkdir ~/bin; fi
cd ~/bin
git clone https://github.com/chhylp123/hifiasm
cd hifiasm
make

#Primero descargamos hifiasm

#Lo ponemos en el PATH permanentemente para que siempre que se inicie bash esté ahi, solo ejecutarlo 1 vez
# echo 'export PATH=$PATH:~/bin/hifiasm' >> ~/.bashrc
# source ~/.bashrc
```

Descargamos el archivo disponible en el aula virtual y lo movemos a data, son una parte de las lecturas HiFi generadas por Rabanal et al. (2022) de un único individuo de la planta Arabidopsis thaliana, ecotipo Columbia (Col-0), con la tecnología SMRT de PacBio.
El archivo está comprimido asi que hay que descomprimirlo:

```{bash}
if [ ! -e ../../data/At4.10.fa ]; then
  gunzip ../../data/At4.10.fa.gz
fi
```

# Revisión de Datos

Los datos están en formato FASTA porque contienen sólo lecturas de alta calidad, y `hifiasm` no utiliza la información de las calidades de cada base. Responde a las siguientes preguntas mediante bloques de Bash o R:

:::{.callout-note icon=false title="Ejercicio 1"}
**¿Cuántas secuencias contiene el archivo?** 

:::{.callout-important icon=false title="Respuesta"}
Se puede utilizar el comando grep para buscar "\>" que hay delante de cada secuencia, eso contará el numero de secuencias
```{bash}
grep -c ">" ../../data/At4.10.fa
```
:::

**¿Qué longitudes mínima, media y máxima tienen las secuencias?**

:::{.callout-important icon=false title="Respuesta"}
Ignoramos las cabeceras "\>" y contamos las bases de cada secuencia, luego se usan para encontrar la secuencia minima, maxima y media
```{bash}
grep -v "^>" ../../data/At4.10.fa | awk '{len=length($0); sum+=len; if(min==""){min=max=len}; if(len<min){min=len}; if(len>max){max=len}; count++} END {print "Mínima:", min; print "Media:", sum/count; print "Máxima:", max}'
```
:::

**¿Cuál es el número total de bases?**

:::{.callout-important icon=false title="Respuesta"}
Eliminamos las cabeceras y los saltos de linea y contamos todos los caracteres
```{bash}
grep -v "^>" ../../data/At4.10.fa | tr -d '\n' | wc -c
```
:::

**Si se estimara que el genoma a ensamblar fuera de sólo 19 millones de bases, ¿cuál sería la cobertura esperada?**

:::{.callout-important icon=false title="Respuesta"}
Calculamos de nuevo la longitud total y la dividimos entre la longitud del genoma a ensamblar para saber cuantas veces ha sido leído (mas o menos)
```{bash}
grep -v "^>" ../../data/At4.10.fa | tr -d '\n' | wc -c | awk '{print $1 / 19000000}'
```
:::
:::

# Ensamblaje

El programa `hifiasm` produce varios archivos de salida. Para tener la carpeta de trabajo ordenada, es recomendable crear un subcarpeta donde poder guardarlos. Si fuéramos a probar más de una estrategia de ensamblado, guardaríamos los resultados de cada intento en una carpeta diferente, que podríamos nombrar `asm1`, `asm2`, etc. Aunque sólo realicemos un ensamblaje, crearemos la carpeta *asm1/* para guardar los resultados en ella.

Crearemos una carpeta para cada estrategia de ensamblado de esta manera:

```{bash}
# Con la ejecución condicional nos ahorramos algún mensaje de error:
if [ ! -d asm1 ]; then mkdir asm1; fi
```

Ahora, para no leer los ensamblajes cada vez que se compile el script
usamos condicionales de bash:

```{bash}
if [ ! -e asm1/At4.bp.p_ctg.gfa ]; then
   ~/bin/hifiasm/hifiasm -o asm1/At4 -t 2 -f 0 ../../data/At4.10.fa 2> asm1/hifiasm.log
fi
```

:::{.callout-note icon=false title="Ejercicio 2"}
Consulta la ayuda de hifiasm (hifiasm -h) y contesta las preguntas
siguientes:
```{bash}
#| eval: false  

~/bin/hifiasm/hifiasm -h
```

**¿Los parámetros corresponden al ensamblaje de un genoma haploide o diploide?** 

:::{.callout-important icon=false title="Respuesta"}
Corresponden a un ensamblaje de un genoma diploide, además el ensmablaje devuelve archivos hap1 y hap2, haciendo alusión a las diferencias entre los haplotipos.
:::

**¿Qué nivel de eliminación de duplicaciones hemos aplicado? (El paso de eliminar duplicaciones sirve para que las zonas de alta heterocigosidad no sean ensambladas como contigs diferentes).** 

:::{.callout-important icon=false title="Respuesta"}
Se utiliza el valor por defecto, ya que no se ha especificado el parámetro -l, es el nivel 0, por lo que no hay purga
:::

**Si tuvieramos lecturas ultra-largas, ¿con qué opción o argumento añadiríamos esa información?** 

:::{.callout-important icon=false title="Respuesta"}
Se añadirían con el argumento --ul
:::
:::

# Evaluación del Resultado

:::{.callout-note icon=false title="Ejercicio 3"}
Consulta la descripción de los archivos de salida que encontrarás en este [enlace](https://hifiasm.readthedocs.io/en/latest/interpreting-output.html) y contesta las preguntas siguientes:

**¿Dónde están las secuencias que componen el ensamblaje?**

:::{.callout-important icon=false title="Respuesta"}
Se encuentran en el archivo At4.bp.p_ctg.gfa
:::

**En los archivos.gfa, ¿qué son las líneas que empiezan por ‘A’?**

:::{.callout-important icon=false title="Respuesta"}
Son lineas que incluyen la información de las lecturas que se usan para construir los contigs, cada una está formada por columnas separadas por tabuladores y contiene información como el nombre del contig, la orientación de la hebra + o -, el nombre de la lectura, los coordenadas de start y end, el ID de la lectura, etc
:::

**¿Qué información tiene los archivos .bed?**

:::{.callout-important icon=false title="Respuesta"}
Son coordenadas de regiones con calidad baja
:::

**¿Cuál es la cobertura media estimada de las secuencias homocigotas?**

:::{.callout-important icon=false title="Respuesta"}
Copiando y pegando del log que devuelve el programa:
\[M::purge_dups\] homozygous read coverage threshold: 12
:::

**¿Y la de las heterocigotas?**

:::{.callout-important icon=false title="Respuesta"}
\[M::ha_ft_gen\] peak_hom: 12; peak_het:-1, esto muestra que no ha encontrado pico heterocigoto, por lo que no se detecta ninguna cobertura, podriamos decir que el organismo de estudio se comporta como un haploide o muy homocigoto
:::
:::

# Los ensamblajes primario y por haplotipos se presentan en formato GFA. Para cambiar el ensamblaje de GFA a FASTA:
```{bash}
awk '(/^S/){print ">" $2 "\n" $3}' asm1/At4.bp.p_ctg.gfa > asm1/At4.fa
```
